### PR TITLE
Fix onFocusChange not called

### PR DESCRIPTION
**Pull request by matteoberla**
Hi, this is a possible fix for issue #50, let me know if it can works.

Basically i've noticed that the callback for focusScope was not registered if the field wasn't tapped.

### CODE REVIEW

**Comment by mytooyo** [comment]
@matteoberla 
1. Tap to focus
2. Press outside to unfocus
3. Select the text until it's all highlighted (don't tap inside the field)
4. Press outside to unfocus

It seems that onFocusChanged is not called in this procedure.

**Comment by matteoberla** [comment]
Yes correct. It's when the text It's hoghlighted without focusing the field first by tapping on it

**Comment by mytooyo** [comment]
Even with this fix, there are still events where the above procedure is not called.

**Comment by matteoberla** [comment]
Which other events are not handled?

**Comment by mytooyo** [comment]
https://github.com/mytooyo/board_datetime_picker/pull/51#issuecomment-2365169216

**Comment by matteoberla** [comment]
With this little change should work as expected, the èproblem was that the flag i added did not reset when the callback function was registered successfully

**Comment by mytooyo** [comment]
Thank you. no problem.

**Pull request merged**
